#!/bin/sh
set -eu
DNSMASQ="$(command -v dnsmasq)"
exec "$DNSMASQ" --keep-in-foreground --port=0 --no-resolv --no-hosts --interface=usb0 --bind-interfaces --dhcp-authoritative --dhcp-range=172.16.42.2,172.16.42.20,255.255.255.0,12h --dhcp-option=3 --dhcp-option=6
